// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LivrariaControleEmprestimo.DATA.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage ="Campo Obrigatório !")]
        [Column("cliCPF")]
        [Display(Name ="CPF")]
        [StringLength(14)]
        public string CliCpf { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("cliNome")]
        [Display(Name = "Nome")]
        [StringLength(200)]
        public string CliNome { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("cliEndereco")]
        [Display(Name = "Endereço")]
        [StringLength(200)]
        public string CliEndereco { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("cliCidade")]
        [Display(Name = "Cidade")]
        [StringLength(100)]
        public string CliCidade { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("cliBairro")]
        [Display(Name = "Bairro")]
        [StringLength(100)]
        public string CliBairro { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("cliNumero")]
        [Display(Name = "Número")]
        [StringLength(50)]
        public string CliNumero { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("cliTeleoneCelular")]
        [Display(Name = "Telefone Celular")]
        [StringLength(20)]
        public string CliTeleoneCelular { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("cliTelefoneFixo")]
        [Display(Name = "Telefone Fixo")]
        [StringLength(20)]
        public string CliTelefoneFixo { get; set; }

        
        [InverseProperty("LceIdClienteNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}