// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace LivrariaControleEmprestimo.DATA.Models
{
    public partial class Livro
    {
        public Livro()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("livroNome")]
        [Display(Name ="Nome Livro")]
        [StringLength(50)]
        public string LivroNome { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("livroAutor")]
        [Display(Name = "Autor")]
        [StringLength(200)]
        public string LivroAutor { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("livroEditora")]
        [Display(Name = "Editora")]
        [StringLength(100)]
        public string LivroEditora { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column("livroAnoPublicacao", TypeName = "datetime")]
        [Display(Name = "Data de Publicação")]
        [DataType(DataType.Date)]
        public DateTime LivroAnoPublicacao { get; set; }

        [Column("livroEdicao")]
        [Display(Name = "Edição")]
        [StringLength(50)]
        public string LivroEdicao { get; set; }


        [InverseProperty("LceIdLivroNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}