// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace LivrariaControleEmprestimo.DATA.Models
{
    [Table("Livro Cliente Emprestimo")]
    public partial class LivroClienteEmprestimo
    {
        [Key]
        public int Id { get; set; }


        public int? LceIdCliente { get; set; }


        public int? LceIdLivro { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column(TypeName = "datetime")]
        [Display(Name = "Data de Retirada")]
        public DateTime? LceDataEmprestimo { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        [Column(TypeName = "datetime")]
        [Display(Name = "Data de Entrga")]
        public DateTime? LceDataEntrega { get; set; }


        [Required(ErrorMessage = "Campo Obrigatório !")]
        public bool? LceEntregue { get; set; }


        [ForeignKey(nameof(LceIdCliente))]
        [InverseProperty(nameof(Cliente.LivroClienteEmprestimo))]
        public virtual Cliente LceIdClienteNavigation { get; set; }


        [ForeignKey(nameof(LceIdLivro))]
        [InverseProperty(nameof(Livro.LivroClienteEmprestimo))]
        public virtual Livro LceIdLivroNavigation { get; set; }
    }
}