// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LivrariaControleEmprestimo.DATA.Models
{
    [Keyless]
    public partial class VwLivroClienteEmprestimo
    {
        [Required]
        [Column("cliCPF")]
        [StringLength(14)]
        [Display(Name ="CPF")]
        public string CliCpf { get; set; }

        [Required]
        [Column("cliNome")]
        [StringLength(200)]
        [Display(Name = "Nome")]
        public string CliNome { get; set; }

        [Required]
        [Column("livroNome")]
        [StringLength(50)]
        [Display(Name = "Livro")]
        public string LivroNome { get; set; }

        public int Id { get; set; }

        public int LceIdCliente { get; set; }

        public int LceIdLivro { get; set; }

        [DataType(DataType.Date)]
        [Column(TypeName = "datetime")]
        [Display(Name = "Saida")]
        public DateTime LceDataEmprestimo { get; set; }

        [DataType(DataType.Date)]
        [Column(TypeName = "datetime")]
        [Display(Name = "Retorno")]
        public DateTime LceDataEntrega { get; set; }

        public bool LceEntregue { get; set; }

        [Required]
        [StringLength(3)]
        [Display(Name = "Atrasado")]
        [Column(TypeName = "LceAtrazo")]
        public string LceAtrazo { get; set; }
    }
}